### ISSUE TITLE
CF API call to delete buildpack_cache returns 404

### ISSUE THREAD

**Issue by michaelgrifalconi** [cloudfoundry-incubator/bits-service#18]
Hello,

please let me know if this should be moved to the capi-release repo.

API call "DELETE /v2/blobstores/buildpack_cache" via cf curl
```
cf curl -X DELETE /v2/blobstores/buildpack_cache
```

It is an async call, so it returns only 'queued' and you need to look at CC logs.
```
{
   "metadata": {
      "guid": "f682730e-1f82-4dfa-b3e9-c1b4d42eb111",
      "created_at": "2019-01-08T13:09:41Z",
      "url": "/v2/jobs/f682730e-1f82-4dfa-b3e9-c1b4d42eb111"
   },
   "entity": {
      "guid": "f682730e-1f82-4dfa-b3e9-c1b4d42eb111",
      "status": "queued"
   }
}
```

On cloud controller logs you can see a 404 error.

```
last_error\" = '{\n  \"response_code\": \"404\"
```
Full log
```
{"timestamp":1546953017.8950722,"message":"(0.002041s) UPDATE \"delayed_jobs\" SET \"guid\" = 'f682730e-1f82-4dfa-b3e9-c1b4d42eb111', \"created_at\" = '2019-01-08 13:09:41.526929+0000', \"updated_at\" = CURRENT_TIMESTAMP, \"priority\" = 4, \"attempts\" = 2, \"handler\" = '--- !ruby/object:VCAP::CloudController::Jobs::LoggingContextJob\nhandler: !ruby/object:VCAP::CloudController::Jobs::TimeoutJob\n  handler: !ruby/object:VCAP::CloudController::Jobs::Runtime::BuildpackCacheCleanup {}\n  timeout: 14400\nrequest_id: 3d837bc2-8c78-4873-5cde-ff6d67e19212::e52c3879-eb08-4d30-b456-80fd734cbdb5\n', \"last_error\" = '{\n  \"response_code\": \"404\",\n  \"response_body\": \"\",\n  \"response\": {\n    \"date\": [\n      \"Tue, 08 Jan 2019 13:09:52 GMT\"\n    ],\n    \"content-length\": [\n      \"0\"\n    ],\n    \"connection\": [\n      \"close\"\n    ]\n  }\n}\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/bits_service_client-3.3.0/lib/bits_service_client/client.rb:175:in `validate_response_code!''\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/bits_service_client-3.3.0/lib/bits_service_client/client.rb:123:in `block in delete_all''\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/bits_service_client-3.3.0/lib/bits_service_client/client.rb:122:in `tap''\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/bits_service_client-3.3.0/lib/bits_service_client/client.rb:122:in `delete_all''\n/var/vcap/data/packages/cloud_controller_ng/f02b1ae156624dd7afb8daa12f85139491c32e94/cloud_controller_ng/app/jobs/runtime/buildpack_cache_cleanup.rb:10:in `perform''\n/var/vcap/data/packages/cloud_controller_ng/f02b1ae156624dd7afb8daa12f85139491c32e94/cloud_controller_ng/app/jobs/wrapping_job.rb:11:in `perform''\n/var/vcap/data/packages/cloud_controller_ng/f02b1ae156624dd7afb8daa12f85139491c32e94/cloud_controller_ng/app/jobs/timeout_job.rb:13:in `block in perform''\n/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout''\n/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/timeout.rb:33:in `block in catch''\n/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/timeout.rb:33:in `catch''\n/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/timeout.rb:33:in `catch''\n/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/timeout.rb:108:in `timeout''\n/var/vcap/data/packages/cloud_controller_ng/f02b1ae156624dd7afb8daa12f85139491c32e94/cloud_controller_ng/app/jobs/timeout_job.rb:12:in `perform''\n/var/vcap/data/packages/cloud_controller_ng/f02b1ae156624dd7afb8daa12f85139491c32e94/cloud_controller_ng/app/jobs/wrapping_job.rb:11:in `perform''\n/var/vcap/data/packages/cloud_controller_ng/f02b1ae156624dd7afb8daa12f85139491c32e94/cloud_controller_ng/app/jobs/logging_context_job.rb:17:in `block in perform''\n/var/vcap/data/packages/cloud_controller_ng/f02b1ae156624dd7afb8daa12f85139491c32e94/cloud_controller_ng/app/jobs/logging_context_job.rb:63:in `with_request_id_set''\n/var/vcap/data/packages/cloud_controller_ng/f02b1ae156624dd7afb8daa12f85139491c32e94/cloud_controller_ng/app/jobs/logging_context_job.rb:15:in `perform''\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job''\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize''\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute''\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks''\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle
```

This was tested on GCP with bits-service-release v2.20.0 and on Azure with 2.18.0.

**Comment by petergtz** [comment]
@michaelgrifalconi I think this is the right repo to raise this issue. We're looking into it.

**Comment by petergtz** [comment]
@michaelgrifalconi This was indeed a bug in our code which we haven't noticed. We'll do a deeper investigation if there are other errors in the CC log which we haven't noticed.

For now, this fix is propagating through our pipelines now and we'll release it later this week or early next week in Bits-Service 2.22.0.

**Comment by petergtz** [comment]
Hi @michaelgrifalconi, we've just released it.

https://bosh.io/releases/github.com/cloudfoundry-incubator/bits-service-release?version=2.22.0 contains the fix for this issue.

Feel free to close this issue once you've verified it works for you. Thank you.

**Comment by michaelgrifalconi** [comment]
Thank you @petergtz, I can confirm that now it works as expected!
